backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "صفحات الموقع"
    files:
      - file: "index.html"
        label: "الصفحة الرئيسية"
        name: "home"
        editor:
          preview: false
        fields:
          - { label: "المحتوى", name: "body", widget: "markdown" }
